### ISSUE TITLE
openBrowser: true when listening on all network interfaces doesn't load the correct URL.

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [divhide/node-grunt-http-server#22]
For instance, using the configuration

        'http-server': {
            dev: {
                root: 'dist/',
                port: 8080,
                host: '0.0.0.0',
                openBrowser: true
            }
        }
will make the browser load the url '0.0.0.0:8080' which is not valid.
Maybe make it in these cases fallback to localhost?

**Comment by aetheon** [comment]
Hi @TiagoOliveiraMarques, I've updated the package with a fix to this problem, available on `grunt-http-server@1.16.0`. Tks for reporting.
